
/* vim: set filetype=c ts=8 noexpandtab: */

#include "common.h"
#include <string.h>
#include "game_sa.h"

static unsigned int airvehicles[7];

void game_sa_init()
{
	memset(airvehicles, 0, sizeof(airvehicles));
#define _ADDAIRVEHICLE(X) airvehicles[(X) / 32] |= ((unsigned int) 1 << ((X) & 31))
#define ADDAIRVEHICLE(X) _ADDAIRVEHICLE(X - 400)
	ADDAIRVEHICLE(MODEL_LEVIATHN);
	ADDAIRVEHICLE(MODEL_HUNTER);
	ADDAIRVEHICLE(MODEL_SEASPAR);
	ADDAIRVEHICLE(MODEL_SKIMMER);
	ADDAIRVEHICLE(MODEL_RCBARON);
	ADDAIRVEHICLE(MODEL_RCRAIDER);
	ADDAIRVEHICLE(MODEL_SPARROW);
	ADDAIRVEHICLE(MODEL_RUSTLER);
	ADDAIRVEHICLE(MODEL_MAVERICK);
	ADDAIRVEHICLE(MODEL_VCNMAV);
	ADDAIRVEHICLE(MODEL_POLMAV);
	ADDAIRVEHICLE(MODEL_RCGOBLIN);
	ADDAIRVEHICLE(MODEL_BEAGLE);
	ADDAIRVEHICLE(MODEL_CROPDUST);
	ADDAIRVEHICLE(MODEL_STUNT);
	ADDAIRVEHICLE(MODEL_SHAMAL);
	ADDAIRVEHICLE(MODEL_HYDRA);
	ADDAIRVEHICLE(MODEL_CARGOBOB);
	ADDAIRVEHICLE(MODEL_NEVADA);
	ADDAIRVEHICLE(MODEL_RAINDANC);
	ADDAIRVEHICLE(MODEL_AT400);
	ADDAIRVEHICLE(MODEL_ANDROM);
	ADDAIRVEHICLE(MODEL_DODO);
}

cell AMX_NATIVE_CALL IsAirVehicle(AMX *amx, cell *params)
{
	int model = params[1] - 400;
	return model != -400 && ((airvehicles[model / 32] >> (model & 31)) & 1);
}

