CREATE TABLE IF NOT EXISTS srv (
	u int(11) NOT NULL,
	s int(11) NOT NULL,
	a varchar(128) NOT NULL,
	PRIMARY KEY (u,s)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE srv ADD CONSTRAINT fk_srv_u FOREIGN KEY (u) REFERENCES usr (i) ON DELETE CASCADE ON UPDATE CASCADE;
